#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# scripts/generate_roms.sh: Generates EmbeddedRoms.h and EmbeddedRoms.cpp from .rom files

set -eu

OUTPUT_DIR="${1:-.}"
ROMS_DIR="${2:-res/roms}"

mkdir -p "$OUTPUT_DIR"

HEADER_FILE="$OUTPUT_DIR/EmbeddedRoms.h"
CPP_FILE="$OUTPUT_DIR/EmbeddedRoms.cpp"

cat <<'EOF' > "$HEADER_FILE"
// SPDX-License-Identifier: GPL-2.0-only
// Auto-generated by scripts/generate_roms.sh - DO NOT EDIT
#pragma once

#include <cstddef>
#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

EOF

cat <<'EOF' > "$CPP_FILE"
// SPDX-License-Identifier: GPL-2.0-only
// Auto-generated by scripts/generate_roms.sh - DO NOT EDIT
#include "EmbeddedRoms.h"

EOF

generate_rom() {
  var_name="$1"
  rom_file="$2"
  macro_guard="$3"

  if [ -f "$rom_file" ]; then
    size=$(wc -c < "$rom_file" | tr -d ' ')
    
    if [ -n "$macro_guard" ]; then
      cat <<EOF >> "$HEADER_FILE"
#if ${macro_guard}
extern const uint8_t ${var_name}[${size}];
extern const size_t ${var_name}_size;
#endif

EOF

      cat <<EOF >> "$CPP_FILE"
#if ${macro_guard}
const size_t ${var_name}_size = ${size};
const uint8_t ${var_name}[${size}] = {
EOF
    else
      cat <<EOF >> "$HEADER_FILE"
extern const uint8_t ${var_name}[${size}];
extern const size_t ${var_name}_size;

EOF

      cat <<EOF >> "$CPP_FILE"
const size_t ${var_name}_size = ${size};
const uint8_t ${var_name}[${size}] = {
EOF
    fi

    # Convert binary to hex literals formatted 16 bytes per line
    od -v -A n -t x1 "$rom_file" | awk '{for(i=1;i<=NF;i++) printf "0x%s, ", $i; printf "\n"}' >> "$CPP_FILE"

    if [ -n "$macro_guard" ]; then
      cat <<EOF >> "$CPP_FILE"
};
#endif

EOF
    else
      cat <<EOF >> "$CPP_FILE"
};

EOF
    fi
  fi
}

generate_rom "g_rom_apple2" "$ROMS_DIR/Apple2.rom" "ENABLE_ROM_APPLE2"
generate_rom "g_rom_apple2_plus" "$ROMS_DIR/Apple2_Plus.rom" "ENABLE_ROM_APPLE2PLUS"
generate_rom "g_rom_apple2e" "$ROMS_DIR/Apple2e.rom" "ENABLE_ROM_APPLE2E"
generate_rom "g_rom_apple2e_enhanced" "$ROMS_DIR/Apple2e_Enhanced.rom" "ENABLE_ROM_APPLE2ENHANCED"
generate_rom "g_rom_apple2e_enhanced_video" "$ROMS_DIR/Apple2e_Enhanced_Video.rom" "ENABLE_ROM_APPLE2ENHANCED"

cat <<'EOF' >> "$HEADER_FILE"
#ifdef __cplusplus
}
#endif
EOF
