#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# scripts/generate_roms.sh: Generates EmbeddedRoms.h and EmbeddedRoms.cpp from .rom files

set -eu

OUTPUT_DIR="${1:-.}"
ROMS_DIR="${2:-res/roms}"

mkdir -p "$OUTPUT_DIR"

HEADER_FILE="$OUTPUT_DIR/EmbeddedRoms.h"
CPP_FILE="$OUTPUT_DIR/EmbeddedRoms.cpp"

cat <<'EOF' > "$HEADER_FILE"
// SPDX-License-Identifier: GPL-2.0-only
// Auto-generated by scripts/generate_roms.sh - DO NOT EDIT
#pragma once

#include <cstddef>
#include <cstdint>

#ifdef __cplusplus
extern "C" {
#endif

EOF

cat <<'EOF' > "$CPP_FILE"
// SPDX-License-Identifier: GPL-2.0-only
// Auto-generated by scripts/generate_roms.sh - DO NOT EDIT
#include "EmbeddedRoms.h"

EOF

generate_rom() {
  var_name="$1"
  rom_file="$2"
  macro_guard="$3"

  if [ -f "$rom_file" ]; then
    size=$(wc -c < "$rom_file" | tr -d ' ')
    
    if [ -n "$macro_guard" ]; then
      cat <<EOF >> "$HEADER_FILE"
#if ${macro_guard}
extern const uint8_t ${var_name}[${size}];
extern const size_t ${var_name}_size;
#endif

EOF

      cat <<EOF >> "$CPP_FILE"
#if ${macro_guard}
const size_t ${var_name}_size = ${size};
const uint8_t ${var_name}[${size}] = {
EOF
    else
      cat <<EOF >> "$HEADER_FILE"
extern const uint8_t ${var_name}[${size}];
extern const size_t ${var_name}_size;

EOF

      cat <<EOF >> "$CPP_FILE"
const size_t ${var_name}_size = ${size};
const uint8_t ${var_name}[${size}] = {
EOF
    fi

    # Convert binary to hex literals formatted 16 bytes per line
    od -v -A n -t x1 "$rom_file" | awk '{for(i=1;i<=NF;i++) printf "0x%s, ", $i; printf "\n"}' >> "$CPP_FILE"

    if [ -n "$macro_guard" ]; then
      cat <<EOF >> "$CPP_FILE"
};
#endif

EOF
    else
      cat <<EOF >> "$CPP_FILE"
};

EOF
    fi
  fi
}

# Official System ROMs
generate_rom "g_rom_apple2" "$ROMS_DIR/Apple2.rom" "ENABLE_ROM_APPLE2"
generate_rom "g_rom_apple2_video" "$ROMS_DIR/Apple2_Video.rom" "ENABLE_ROM_APPLE2"
generate_rom "g_rom_apple2_plus" "$ROMS_DIR/Apple2_Plus.rom" "ENABLE_ROM_APPLE2PLUS"
generate_rom "g_rom_apple2_jplus" "$ROMS_DIR/Apple2_JPlus.rom" "ENABLE_ROM_APPLE2_JPLUS"
generate_rom "g_rom_apple2_jplus_video" "$ROMS_DIR/Apple2_JPlus_Video.rom" "ENABLE_ROM_APPLE2_JPLUS"
generate_rom "g_rom_apple2e" "$ROMS_DIR/Apple2e.rom" "ENABLE_ROM_APPLE2E"
generate_rom "g_rom_apple2e_enhanced" "$ROMS_DIR/Apple2e_Enhanced.rom" "ENABLE_ROM_APPLE2ENHANCED"
generate_rom "g_rom_apple2e_enhanced_video" "$ROMS_DIR/Apple2e_Enhanced_Video.rom" "ENABLE_ROM_APPLE2ENHANCED"

# Third-Party Clones
generate_rom "g_rom_clone_base64a" "$ROMS_DIR/Base64A.rom" "ENABLE_ROM_CLONE_BASE64A"
generate_rom "g_rom_clone_base64a_german_video" "$ROMS_DIR/Base64A_German_Video.rom" "ENABLE_ROM_CLONE_BASE64A"
generate_rom "g_rom_clone_pravets82" "$ROMS_DIR/PRAVETS82.ROM" "ENABLE_ROM_CLONE_PRAVETS"
generate_rom "g_rom_clone_pravets8c" "$ROMS_DIR/PRAVETS8C.ROM" "ENABLE_ROM_CLONE_PRAVETS"
generate_rom "g_rom_clone_pravets8m" "$ROMS_DIR/PRAVETS8M.ROM" "ENABLE_ROM_CLONE_PRAVETS"
generate_rom "g_rom_clone_tk3000e" "$ROMS_DIR/TK3000e.rom" "ENABLE_ROM_CLONE_TK3000E"

# Peripheral ROMs
generate_rom "g_rom_disk2" "$ROMS_DIR/DISK2.rom" "ENABLE_ROM_DISK2"
generate_rom "g_rom_disk2_13sector" "$ROMS_DIR/DISK2-13sector.rom" "ENABLE_ROM_DISK2"
generate_rom "g_rom_ssc" "$ROMS_DIR/SSC.rom" "ENABLE_ROM_SSC"
generate_rom "g_rom_mouse_interface" "$ROMS_DIR/MouseInterface.rom" "ENABLE_ROM_MOUSE"
generate_rom "g_rom_mockingboard_d" "$ROMS_DIR/Mockingboard-D.rom" "ENABLE_ROM_MOCKINGBOARD"
generate_rom "g_rom_parallel" "$ROMS_DIR/Parallel.rom" "ENABLE_ROM_PRINTER"
generate_rom "g_rom_thunderclock_plus" "$ROMS_DIR/ThunderClockPlus.rom" "ENABLE_ROM_CLOCK"
generate_rom "g_rom_tkclock" "$ROMS_DIR/TKClock.rom" "ENABLE_ROM_CLOCK"

cat <<'EOF' >> "$HEADER_FILE"
#ifdef __cplusplus
}
#endif
EOF
